package main

import (
	"github.com/gin-contrib/cors"
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"     // swagger embed files
	ginSwagger "github.com/swaggo/gin-swagger" // gin-swagger middleware

	"playground/controllers"
	_ "playground/docs" // swagger docs generated by Swag CLI
)

// @title Go Web API Playground
// @version 1.0
// @description This is a playground Web API using Gin framework.
// @BasePath /api/v1
func main() {
	r := setupRouter()
	r.Run() // listen and serve on 0.0.0.0:8080 (for windows "localhost:8080")
}

func setupRouter() *gin.Engine {
	r := gin.Default()

	// CORS Configuration
	config := cors.DefaultConfig()
	config.AllowOrigins = []string{"http://localhost:4200"}
	r.Use(cors.New(config))

	// Swagger Configuration
	c := controllers.NewController()

	v1 := r.Group("/api/v1")
	{
		examples := v1.Group("/examples")
		{
			examples.GET("ping", c.PingExample)
		}
		lyrics := v1.Group("/lyrics")
		{
			lyrics.GET(":artist/:song", c.GetLyrics)
		}
	}

	url := ginSwagger.URL("http://localhost:8080/swagger/doc.json") // The url pointing to API definition
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler, url))

	return r
}
